
_tune1:
; start tune 'aadams'
                retlw   0x88    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x0a    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x0a    ; d
                retlw   0x88    ; f
                retlw   0x05    ; d
                retlw   0x80    ; f
                retlw   0x0a    ; d
                retlw   0xaf    ; f
                retlw   0x13    ; d
                retlw   0xa6    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x0a    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x0a    ; d
                retlw   0x41    ; f
                retlw   0x05    ; d
                retlw   0x71    ; f
                retlw   0x0a    ; d
                retlw   0xa6    ; f
                retlw   0x13    ; d
                retlw   0x88    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x0a    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x0a    ; d
                retlw   0x88    ; f
                retlw   0x05    ; d
                retlw   0x80    ; f
                retlw   0x0a    ; d
                retlw   0xaf    ; f
                retlw   0x13    ; d
                retlw   0xa6    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x0a    ; d
                retlw   0x88    ; f
                retlw   0x05    ; d
                retlw   0x95    ; f
                retlw   0x0a    ; d
                retlw   0xa0    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x26    ; d
                retlw   0xff    ; end
                retlw   0x00    ; CD
                retlw   0xfe
; end tune 'aadams'

_tune2:
; start tune 'Bolero'
                retlw   0xc3    ; f
                retlw   0x13    ; d
                retlw   0xc3    ; f
                retlw   0x0a    ; d
                retlw   0xc0    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xc0    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x0a    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x13    ; d
                retlw   0xc3    ; f
                retlw   0x0a    ; d
                retlw   0xc0    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x26    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x05    ; d
                retlw   0x95    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x13    ; d
                retlw   0xaf    ; f
                retlw   0x13    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xc0    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x05    ; d
                retlw   0x95    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x05    ; d
                retlw   0x95    ; f
                retlw   0x05    ; d
                retlw   0x88    ; f
                retlw   0x0a    ; d
                retlw   0x88    ; f
                retlw   0x0a    ; d
                retlw   0x88    ; f
                retlw   0x05    ; d
                retlw   0x95    ; f
                retlw   0x05    ; d
                retlw   0xa0    ; f
                retlw   0x0a    ; d
                retlw   0xa6    ; f
                retlw   0x0a    ; d
                retlw   0x95    ; f
                retlw   0x13    ; d
                retlw   0xaf    ; f
                retlw   0x26    ; d
                retlw   0xff    ; end
                retlw   0x00    ; CD
                retlw   0xfe
; end tune 'Bolero'

_tune3:
; start tune 'getred'
                retlw   0xaf    ; f
                retlw   0x09    ; d
                retlw   0xaf    ; f
                retlw   0x09    ; d
                retlw   0xaf    ; f
                retlw   0x06    ; d
                retlw   0x88    ; f
                retlw   0x06    ; d
                retlw   0x88    ; f
                retlw   0x06    ; d
                retlw   0x95    ; f
                retlw   0x06    ; d
                retlw   0x95    ; f
                retlw   0x06    ; d
                retlw   0xaf    ; f
                retlw   0x09    ; d
                retlw   0xaf    ; f
                retlw   0x09    ; d
                retlw   0xaf    ; f
                retlw   0x06    ; d
                retlw   0xbc    ; f
                retlw   0x06    ; d
                retlw   0xbc    ; f
                retlw   0x06    ; d
                retlw   0xc3    ; f
                retlw   0x06    ; d
                retlw   0xc3    ; f
                retlw   0x06    ; d
                retlw   0xaf    ; f
                retlw   0x09    ; d
                retlw   0xaf    ; f
                retlw   0x09    ; d
                retlw   0xaf    ; f
                retlw   0x06    ; d
                retlw   0x88    ; f
                retlw   0x06    ; d
                retlw   0x88    ; f
                retlw   0x06    ; d
                retlw   0x95    ; f
                retlw   0x06    ; d
                retlw   0x95    ; f
                retlw   0x06    ; d
                retlw   0xaf    ; f
                retlw   0x09    ; d
                retlw   0xaf    ; f
                retlw   0x09    ; d
                retlw   0xaf    ; f
                retlw   0x06    ; d
                retlw   0xbc    ; f
                retlw   0x06    ; d
                retlw   0xbc    ; f
                retlw   0x06    ; d
                retlw   0xc3    ; f
                retlw   0x06    ; d
                retlw   0xca    ; f
                retlw   0x06    ; d
                retlw   0xff    ; end
                retlw   0x00    ; CD
                retlw   0xfe
; end tune 'getred'

_tune4:
; start tune 'Looney'
                retlw   0xc3    ; f
                retlw   0x0b    ; d
                retlw   0xd2    ; f
                retlw   0x05    ; d
                retlw   0xd0    ; f
                retlw   0x05    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x10    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xd2    ; f
                retlw   0x05    ; d
                retlw   0xd0    ; f
                retlw   0x05    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xcd    ; f
                retlw   0x05    ; d
                retlw   0xd0    ; f
                retlw   0x10    ; d
                retlw   0xd0    ; f
                retlw   0x05    ; d
                retlw   0xd0    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xd0    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0xbc    ; f
                retlw   0x05    ; d
                retlw   0xb8    ; f
                retlw   0x05    ; d
                retlw   0xa6    ; f
                retlw   0x05    ; d
                retlw   0xff    ; end
                retlw   0x00    ; CD
                retlw   0xfe
; end tune 'Looney'

_tune5:
; start tune 'Money'
                retlw   0xd0    ; f
                retlw   0x07    ; d
                retlw   0xd0    ; f
                retlw   0x07    ; d
                retlw   0xd0    ; f
                retlw   0x07    ; d
                retlw   0xd0    ; f
                retlw   0x07    ; d
                retlw   0xd0    ; f
                retlw   0x07    ; d
                retlw   0xd0    ; f
                retlw   0x07    ; d
                retlw   0xa0    ; f
                retlw   0x03    ; d
                retlw   0xb8    ; f
                retlw   0x03    ; d
                retlw   0xc3    ; f
                retlw   0x03    ; d
                retlw   0xd0    ; f
                retlw   0x03    ; d
                retlw   0xcd    ; f
                retlw   0x07    ; d
                retlw   0xcd    ; f
                retlw   0x07    ; d
                retlw   0xcd    ; f
                retlw   0x07    ; d
                retlw   0xcd    ; f
                retlw   0x07    ; d
                retlw   0xcd    ; f
                retlw   0x07    ; d
                retlw   0xcd    ; f
                retlw   0x07    ; d
                retlw   0xa6    ; f
                retlw   0x03    ; d
                retlw   0xb8    ; f
                retlw   0x03    ; d
                retlw   0xc3    ; f
                retlw   0x03    ; d
                retlw   0xcd    ; f
                retlw   0x03    ; d
                retlw   0xca    ; f
                retlw   0x0e    ; d
                retlw   0xc3    ; f
                retlw   0x07    ; d
                retlw   0xb8    ; f
                retlw   0x07    ; d
                retlw   0xc3    ; f
                retlw   0x07    ; d
                retlw   0xc3    ; f
                retlw   0x0e    ; d
                retlw   0xb8    ; f
                retlw   0x1b    ; d
                retlw   0xb8    ; f
                retlw   0x02    ; d
                retlw   0xc3    ; f
                retlw   0x02    ; d
                retlw   0xd0    ; f
                retlw   0x02    ; d
                retlw   0xdb    ; f
                retlw   0x07    ; d
                retlw   0xff    ; end
                retlw   0x00    ; CD
                retlw   0xfe
; end tune 'Money'

_tune6:
; start tune 'Popcorn'
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xbc    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0x9b    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0x88    ; f
                retlw   0x0a    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xbc    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0x9b    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0x88    ; f
                retlw   0x0a    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xcd    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x02    ; d
                retlw   0xcd    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x02    ; d
                retlw   0xcd    ; f
                retlw   0x05    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xbc    ; f
                retlw   0x02    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xbc    ; f
                retlw   0x02    ; d
                retlw   0xca    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x05    ; d
                retlw   0xbc    ; f
                retlw   0x05    ; d
                retlw   0xaf    ; f
                retlw   0x05    ; d
                retlw   0xbc    ; f
                retlw   0x05    ; d
                retlw   0xc3    ; f
                retlw   0x0a    ; d
                retlw   0xff    ; end
                retlw   0x00    ; CD
                retlw   0xfe
; end tune 'Popcorn'

_tune7:
; start tune 'Smoke'
                retlw   0x88    ; f
                retlw   0x0e    ; d
                retlw   0x9b    ; f
                retlw   0x0e    ; d
                retlw   0xa6    ; f
                retlw   0x15    ; d
                retlw   0x88    ; f
                retlw   0x0e    ; d
                retlw   0x9b    ; f
                retlw   0x0e    ; d
                retlw   0xab    ; f
                retlw   0x07    ; d
                retlw   0xa6    ; f
                retlw   0x0e    ; d
                retlw   0x00    ; f
                retlw   0x0e    ; d
                retlw   0x88    ; f
                retlw   0x0e    ; d
                retlw   0x9b    ; f
                retlw   0x0e    ; d
                retlw   0xa6    ; f
                retlw   0x15    ; d
                retlw   0x9b    ; f
                retlw   0x0e    ; d
                retlw   0x88    ; f
                retlw   0x0e    ; d
                retlw   0xff    ; end
                retlw   0x00    ; CD
                retlw   0xfe
; end tune 'Smoke'
